/** @type {import('tailwindcss').Config} */
const { cpcHex } = require("./lib/design/cpc-hex.cjs");

// CPC tokens — hex NativeWind (RN). Canonical OKLCH: lib/design/cpc-tokens.ts
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: {
          DEFAULT: cpcHex.background,
          soft: cpcHex.elevated,
          elevated: cpcHex.elevated,
          card: cpcHex.card,
          secondary: cpcHex.secondary,
          glass: "rgba(8,14,20,0.72)",
        },
        border: {
          DEFAULT: cpcHex.border,
          soft: cpcHex.borderSubtle,
          active: cpcHex.secondary,
          cinematic: "rgba(84,225,130,0.35)",
        },
        accent: {
          DEFAULT: cpcHex.accent,
          50: "#e9fff3",
          100: "#c6ffe0",
          200: "#8dffc2",
          300: "#7aeba0",
          400: cpcHex.accent,
          500: cpcHex.success,
          600: "#12b559",
          700: "#0e8c46",
          800: "#0c6d38",
          900: "#0a562d",
          fg: cpcHex.accentForeground,
          soft: "rgba(84,225,130,0.12)",
        },
        live: {
          DEFAULT: cpcHex.live,
          soft: "rgba(249,65,68,0.12)",
        },
        success: {
          DEFAULT: cpcHex.success,
          soft: "rgba(92,212,129,0.12)",
        },
        outcome: {
          win: { DEFAULT: cpcHex.success, soft: "rgba(92,212,129,0.12)" },
          draw: { DEFAULT: cpcHex.warning, soft: "rgba(252,181,44,0.12)" },
          loss: { DEFAULT: cpcHex.error, soft: "rgba(234,60,63,0.12)" },
        },
        pro: {
          DEFAULT: "#8b5cf6",
          50: "#f4f0ff",
          100: "#e6dbff",
          200: "#cdb6ff",
          300: "#ae8bff",
          400: "#8b5cf6",
          500: "#7238ea",
          600: "#5c26c9",
          700: "#481c9e",
          800: "#37177a",
          900: "#291360",
        },
        rarity: {
          bronze: "#a3673a",
          silver: "#c0c5cc",
          gold: "#e8b84b",
          icon: "#39e6ff",
        },
        danger: cpcHex.error,
        warn: cpcHex.warning,
        disabled: cpcHex.disabled,
        pitch: {
          DEFAULT: cpcHex.pitch,
          deep: cpcHex.pitchDeep,
          line: cpcHex.pitchLine,
        },
        overlay: cpcHex.overlay,
        fg: {
          DEFAULT: cpcHex.textPrimary,
          secondary: cpcHex.textSecondary,
          muted: cpcHex.textMuted,
          subtle: cpcHex.disabled,
        },
      },
      borderRadius: {
        none: "0px",
        control: "2px",
        card: "0px",
        badge: "2px",
        input: "4px",
        sheet: "16px",
        phone: "28px",
        xl2: "20px",
      },
      fontSize: {
        micro: ["9px", { lineHeight: "12px" }],
        caption: ["10px", { lineHeight: "14px" }],
        eyebrow: ["11px", { lineHeight: "16px", letterSpacing: "1.32px" }],
        bodySmall: ["12px", { lineHeight: "20px" }],
        body: ["14px", { lineHeight: "24px" }],
        action: ["16px", { lineHeight: "20px" }],
        titleSmall: ["20px", { lineHeight: "24px" }],
        title: ["24px", { lineHeight: "28px" }],
        displaySmall: ["30px", { lineHeight: "30px" }],
        display: ["36px", { lineHeight: "36px" }],
        displayLarge: ["48px", { lineHeight: "44px" }],
        timer: ["72px", { lineHeight: "72px" }],
      },
      spacing: {
        13: "52px",
        15: "60px",
        18: "72px",
      },
      minHeight: {
        touch: "44px",
        button: "44px",
        "button-lg": "52px",
        header: "64px",
        nav: "78px",
      },
      minWidth: {
        touch: "44px",
      },
      fontFamily: {
        display: ["BarlowCondensed_700Bold"],
        "display-semibold": ["BarlowCondensed_600SemiBold"],
        "display-extrabold": ["BarlowCondensed_700Bold"],
        "display-black": ["BarlowCondensed_700Bold"],
        sans: ["Inter_400Regular"],
        "sans-medium": ["Inter_500Medium"],
        "sans-semibold": ["Inter_600SemiBold"],
        "sans-bold": ["Inter_700Bold"],
      },
    },
  },
  plugins: [],
};
